### ISSUE TITLE
Should work with iOS app too

### ISSUE THREAD

**Issue by zedtux** [Jems22/fastlane-plugin-get_version_code#3]
Given I have react-native app with an iOS and Android app and I'm managing different versions for both, while this gem is 100% what is required for the Android app, it would be great to be able to use it for iOS too so that the fastlane it could be used in both platforms.

**Comment by oklimberg** [comment]
Can't you use the build in action from fastlane for iOS? 
I am not familiar with react-native project structure, so some more information would help.

**Comment by zedtux** [comment]
Not really sure to understand your question.

This plugin works with Android, not iOS. What else can I give you in order to help?

**Comment by oklimberg** [comment]
Does the iOS part of the react-native project also use the gradle build system? Or does it have a xcodeproj file?
If it does, you might be able to use the build in [get_version_number](https://docs.fastlane.tools/actions/get_version_number/) action from fastlane

**Comment by zedtux** [comment]
It has a xcodeproj file, but the `get_version_number` didn't worked for me, that's why I've opened this issue.

If you look at the [get_version_code_action.rb](https://github.com/Jems22/fastlane-plugin-get_version_code/blob/master/lib/fastlane/plugin/get_version_code/actions/get_version_code_action.rb) source code, you'll see that it looks only for gradle files.
My issue is about to add some code (and probably tests for both Android and iOS) so that it can get the version code from iOS project too.

**Comment by oklimberg** [comment]
Of course this plugin only works for Android because it is a port for Android based on the built-in action of fastlane (linked above), which works only for iOS. I will not add functionality to support iOS if there is already such functionality in fastlane itself.

By the way, [get_version_number](https://docs.fastlane.tools/actions/get_version_number/) works totally fine for me in various iOS projects. But if there is an issue with the fastlane action, an issue in the fastlane repository would be more promising.
You could alternatively use [get_info_plist_value](https://docs.fastlane.tools/actions/get_info_plist_value/) to read the value manually from the info.plist yourself.

**Comment by zedtux** [comment]
> Of course this plugin only works for Android because it is a port for Android based on the built-in action of fastlane (linked above), which works only for iOS. I will not add functionality to support iOS if there is already such functionality in fastlane itself.

Well that make sense if it's true. I'm not and I will not work on this project in the next weeks so I can't give it a try but I'm quite confident that if I've open this issue, it was because I had to use this plugin because, I guess, it wasn't working.
The other option is that I wanted to get the version code the same way for both platform.

Question: In the case fastlane has a working way to get the version code, why is it a plugin for Android? Why don't you open a merge request?
That would make a lot of sense to get ride of this plugin by merging it and avoiding this kind of confusion.

> You could alternatively use get_info_plist_value to read the value manually from the info.plist yourself.

As I said previously, I want to stay away from various ways for getting the same info.

> I will not add functionality to support iOS if there is already such functionality in fastlane itself.

If you strongly believe in this, then rename the plugin with "Android" in the name and also update the `README.md` file reflecting what you said so that people know about it.

**Comment by oklimberg** [comment]
Hi, I think there is a misunderstanding:

> Question: In the case fastlane has a working way to get the version code, why is it a plugin for Android?

Fastlane has a set of **built-in** actions which are listed [here](https://docs.fastlane.tools/actions/). One of them is [get_version_number](https://docs.fastlane.tools/actions/get_version_number/) which will read the CFBundleShortVersionString from the Info.plist of Xcode projects.
But comparing iOS and Android, the Android versionCode corresponds more to the bundle version  (CFBundleVersion) of Xcode projects so the the action i should have linked would be [get_build_number](https://docs.fastlane.tools/actions/get_build_number/). Both actions only work for Xcode projects and **not** Android.
This is the reason, why the author created this plugin.

>Why don't you open a merge request?
That would make a lot of sense to get ride of this plugin by merging it and avoiding this kind of confusion.

I just started to maintain this project. After updating the documentation I might create a pull request so this action might be added to fastlane directly. But I do not know if I will find the time for this.

>If you strongly believe in this, then rename the plugin with "Android" in the name and also update the README.md file reflecting what you said so that people know about it.

The documentation is only minimal at the moment but it clearly states, it will get the versionCode on Android projects. Nonetheless, I plan on updating the documentation, to reflect this fact even more.

I appreciate the time you take to give me this feedback

**Comment by zedtux** [comment]
> After updating the documentation I might create a pull request so this action might be added to fastlane directly.

As soon as you do it, please let me know, I'd like to upvote it and follow up on it in order to help you to get ride of this plugin, avoiding to have a plugin where something exist internally and should work for both platform.
