### ISSUE TITLE
 Get version clode returns method name from gradle

### ISSUE THREAD

**Issue by radekstasiak** [Jems22/fastlane-plugin-get_version_code#5]
Hi,

In my build.gradle file I specify version code in following way:
`versionCode computeVersionCode()`

where computeVersionName() is a method 
`def computeVersionCode() {
return (vMajor * 10000) + (vMinor * 1000) + (vMinorMinor * 100) + Integer.valueOf(System.env.BUILD_NUMBER ?: 0)
}`

Calling get_version_code returns string "computeVersionCode()" instead of the method result.

**Comment by oklimberg** [comment]
I do not know if this can be 'fixed'. Gradle is not involved at all when reading the versionCode, and the built-in gradle action only supports tasks to be called.
I had a quick look into another plugin for Android and it has the same limitations.

**Comment by oklimberg** [comment]
After some more research, your best bet would be to write a custom task wrapping your method 
`computeVersionCode()` This could then be called using `gradle(task: yourWrapperTask)`

I will add this limitation and maybe my suggested workaround to the documentation.
